# Header
menu:
  Home: /
  会の紹介(Introduction): /introduction
  活動記録(Activity): /activity
  山行予定(Plan): /plan
  入会案内(Admission): /admission
rss: 

# Content
excerpt_link: Read More
fancybox: true

# Sidebar
sidebar: right
widgets:
- links
- tag
- tagcloud
- archive
- recent_posts

links:
- {url: http://sangaku-osaka.com/link.html, title: 大阪府山岳連盟}
- {url: http://cca-azumino.sakura.ne.jp/, title: 登攀クラブ安曇野}
- {url: http://gcn.byoubu.com/old.html, title: 旧サイト}


# display widgets at the bottom of index pages (pagination == 2)
index_widgets:
# - category
# - tagcloud
# - archive

# widget behavior
archive_type: 'monthly'
show_count: false

# Miscellaneous
google_analytics:
gauges_analytics:
favicon: /favicon.ico
twitter:
google_plus:
fb_admins:
fb_app_id:
