#!/bin//bash
file=$1

year=`echo $file | cut -c -4`
month=`echo $file | cut -c 5-6`
day=`echo $file | cut -c 7-8`
base=`echo $file | cut -d. -f 1`


cat $file | sed -e "/]([^/]/{s!](!](/$year/$month/$day/$base/!}" > $file.bak
mv $file.bak $file
